"""Internal Lighter and Robinhood Chain constants."""

API_BASE_URL = "https://api.rh.lighter.xyz"
CHAIN_ID = 466324

ROBINHOOD_CHAIN_ID = 4663
ROBINHOOD_RPC_URL = "https://rpc.mainnet.chain.robinhood.com"
DEPOSIT_TOKEN_SYMBOL = "USDG"

DEFAULT_API_KEY_INDEX = 4
API_KEY_ACTIVATION_WAIT_SECONDS = 10
REFERRAL_CODE = "RUD3WAVE"
REFERRAL_X = ""

DEPOSIT_WAIT_FOR_RECEIPT = True
POST_DEPOSIT_ACCOUNT_POLL_ATTEMPTS = 20
POST_DEPOSIT_ACCOUNT_POLL_SECONDS = 30

SPREAD_LOG_INTERVAL_SECONDS = 15
SPREAD_WAIT_TIMEOUT_SECONDS = 180
HEDGE_SETTLE_SECONDS = 1.5
RESIDUAL_CLOSE_RETRIES = 3
